import React, { useState, useEffect, useRef } from 'react'
import '../App.css'
import '../styles/MainContainer.css'
import './aboutus.css'
import 'react-datepicker/dist/react-datepicker.css'
import TopBar from '../components/TopBar.jsx'
import graph from '../../public/img/Bonding Curve.png'
import logo from '../../public/img/coollogo_com-22031459.png'
import footericon from '../../public/img/hot.png'
import arrow from '../../public/img/Yellow Arrow.png'
import arrowup from '../../public/img/Yellow Arrow-up.png'
import Footer from '../components/Footer.jsx'
function Privacy() {
    const [visibleSection, setVisibleSection] = useState(null) // Manages which section is visible

    const toggleVisibility = section => {
        if (visibleSection === section) {
            setVisibleSection(null) // Close the section if it's already open
        } else {
            setVisibleSection(section) // Open the clicked section and close others
        }
    }
    return (
        <div>
            <div className="GlobalContainer">
                <div style={{ zIndex: 1 }}>
                    <TopBar />
                    <div>
                        <div className="max-w-7xl mx-auto pt-36 px-4 sm:px-12 sm:py-4">
                            <section className="lg:mx-auto  w-full lg:w-[741px] min-w-0">
                                <div
                                    style={{
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center'
                                    }}
                                >
                                    {/* <img style={{ height: '113px' }} src={logo} /> */}
                                    <div
                                        className="text-center text-[#f3f3f3] text-xl mb-1.5 impact-headings"
                                        style={{
                                            fontSize: '60px',
                                            fontWeight: 'bold',
                                            marginBottom: '30px'
                                        }}
                                    >
                                        Privacy Policy for STARWIN
                                    </div>
                                </div>

                            </section>
                        </div>
                        <div className="max-w-7xl m-auto pb-24 px-4 sm:px-12">

                            <div className="lg:mx-auto  w-full lg:w-[741px] min-w-0">

                                <div className="list-disc pl-3 space-y-1 text-white mb-5">
                                    <p className="text-white">STARWIN ("we," "us," or "our") is committed to protecting the privacy of our users ("you"
                                        or "your"). This Privacy Policy explains how we collect, use, and share your personal
                                        information1 when you visit or use our website, https://starwin.money (the "Site"). We
                                        encourage you to read this policy carefully.:</p>
                                    <br></br>
                                    <br></br>

                                    <p className="text-white">
                                        1. Privacy Policy
                                        <br></br>
                                        <br></br>
                                        Limited data protection is a matter of trust and your privacy is very important to us. We use
                                        your information only in the manner set out in this privacy policy. Please read this privacy
                                        policy to learn more about our information-gathering and dissemination practices. The
                                        privacy practices of this statement apply to services available under this domain, sub-domains
                                        and shall apply to generally the websites generated by us, our affiliates, our subsidiaries or
                                        our joint ventures if any. By visiting the site, you agree to be bound by the terms and
                                        conditions of this privacy policy. This privacy policy explains how we gather information
                                        either mandatory or optional as part of the normal business procedure. This detailed privacy
                                        policy enables you to make informed decisions in dealings with us.
                                        <br></br>
                                        <br></br>
                                        By browsing the website, you acknowledge your acceptance of the terms of this privacy
                                        policy and give an express consent to our use and disclosure of your information in
                                        accordance with this privacy policy and that any information provided by you through the
                                        website is provided under a lawful contract.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        2. Privacy Assurance
                                        <br></br>
                                        <br></br>
                                        Your trust and privacy protection are our highest priority. We promise that we will not trade
                                        your information with third parties without your explicit consent. From time to time, we may
                                        reveal general statistical information about our website visitors, such as a number of visitors,
                                        page views, and type of products and services purchased, etc. We may provide the collected
                                        information to our affiliates and service providers under contract (such as customer care, data
                                        analytics) to support the operation of our business. To some extent, we may use your
                                        information to market you.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        3. Disclosure of Information
                                        <br></br>
                                        <br></br>
                                        Your information is an important part of our business and we are not in the business of
                                        selling information to others. Our site shares your information only to categories of persons
                                        that are either subject to this privacy policy or follow practices as protective as those
                                        described in this privacy policy. We share much of our data, including information about you,
                                        with our affiliates, our subsidiaries or our joint ventures that are committed to serving your
                                        online needs and related services. To the extent that these entities have access to your
                                        information, they remain bound by this privacy policy. As we continue to develop our
                                        business, we might sell some part of it. In such transactions, your information generally is
                                        one of the transferred business assets but remains subject to the promises made in any preexisting privacy policy.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        4. Types of Information
                                        <br></br>
                                        <br></br>
                                        In our efforts to continually improve our offerings, we collect and analyse demographic,
                                        profile and usage data about the users’ activity on our site. If you choose to post messages on
                                        our message boards, chat rooms or other message areas or leave feedback for other users, we
                                        retain this information as necessary to resolve disputes, provide customer support and
                                        troubleshoot problems as permitted by law. If you send us personal correspondence, such as
                                        emails or letters, we may collect such information also. We collect information about how
                                        you use our Site, such as the pages you visit, the games you play, and the links you click.
                                        This may include your IP address, browser type, device information, and referring website.
                                        We may collect information about your location, such as your IP address, which may be used
                                        to personalize your experience and ensure compliance with local regulations. We use cookies,
                                        web beacons, and other tracking technologies to collect information about3 your activity on
                                        our Site. These technologies help us personalize your experience, analyse site usage, and
                                        serve targeted advertising. You can control cookies through your browser settings, but
                                        disabling cookies may affect the functionality of our site.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        5. How We Use Your Information:
                                        <br></br>
                                        <br></br>
                                        We use your information for the following purposes:
                                        <br></br>
                                        <br></br>
                                        <ul className="list-disc pl-3">
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Providing Services: To provide you with access to our lottery games, process your
                                                    ticket purchases, manage your account, and deliver prizes.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Customer Support: To respond to your inquiries and provide customer support.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Legal Compliance: To comply with applicable laws and regulations, including age
                                                    verification and anti-money laundering requirements.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Marketing and Promotions: With your consent, we may send you marketing
                                                    communications about our games, promotions, and other offers.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Improving the Site: To analyse site usage and improve the functionality and user
                                                    experience of our Site.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Security: To protect the security and integrity of our Site and prevent fraud.
                                                </p>
                                            </li>
                                        </ul>
                                        <br></br>
                                        <br></br>
                                        6. Sharing Your Information:
                                        <br></br>
                                        <br></br>
                                        We may share your information with the following third parties:
                                        <br></br>
                                        <br></br>
                                        <ul className="list-disc pl-3">
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Service Providers: We may share your information with third-party service providers
                                                    who assist us with payment processing, customer support, data analytics, marketing,
                                                    and other services. We require these service providers to protect your information and
                                                    only use it for the purposes we specify.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Government Authorities: We may disclose your information to government
                                                    authorities if required by law or legal process, or if we believe it is necessary to
                                                    protect our legal rights or the rights of others.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Legal Compliance: To comply with applicable laws and regulations, including age
                                                    verification and anti-money laundering requirements.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Business Transfers: If we are involved in a merger, acquisition, or sale of all or a
                                                    portion of our assets, your information6 may be transferred as part of that transaction.
                                                </p>
                                            </li>
                                            <li className="mb-0 ml-6">
                                                <p className="text-white">
                                                    Lottery Operators/Regulators: We may share information with the official lottery
                                                    operator and regulatory bodies as required by law and for the administration of the
                                                    lottery games.
                                                </p>
                                            </li>

                                        </ul>
                                        <br></br>
                                        <br></br>
                                        7. Legal Request
                                        <br></br>
                                        <br></br>
                                        We cooperate with law enforcement and regulatory inquiries, such as intellectual property
                                        rights, fraud, and other rights, to help protect you and the community from bad actors.
                                        Therefore, in response to a verified request by law enforcement or other regulatory authorities
                                        relating to a criminal investigation or alleged illegal activity, we may (and you authorize us
                                        to) disclose some/all of your information as is reasonably necessary to respond to court orders
                                        or other legal proceedings.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        8. Instruction Related to Minors
                                        <br></br>
                                        <br></br>
                                        Our Site is not intended for children under the age of 18. If you are under the age of 18, you
                                        cannot use the services of this site. We do not knowingly allow playing or collect personal
                                        information from children under 18. We reserve the right to request proof of age from any
                                        customer and may suspend an account until adequate verification is received.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        9. Data Security:
                                        <br></br>
                                        <br></br>
                                        We take reasonable measures to protect your information from unauthorized access, use, or
                                        disclosure. However, no method of transmission over the Internet, or method of electronic
                                        storage, is 100% secure.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        10. Changes to this Privacy Policy:
                                        <br></br>
                                        <br></br>
                                        We may update this Privacy Policy from time to time. We will post any changes on this page
                                        and notify you as required by law.
                                        <br></br>
                                        <br></br>
                                        <br></br>
                                        11. Contact Us:
                                        <br></br>
                                        <br></br>
                                        If you have any questions about this Privacy Policy, please contact us at:
                                        <br></br>
                                        info@starwin.money
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export default Privacy
